import { existsSync, readFileSync, writeFileSync, chmodSync } from 'node:fs';
import { WalletBuilder } from '@midnight-ntwrk/wallet';
import { NetworkId } from '@midnight-ntwrk/zswap';

export const ENDPOINTS = {
  indexer: process.env.INDEXER_URL ?? 'https://indexer.preprod.midnight.network/api/v4/graphql',
  indexerWs: process.env.INDEXER_WS_URL ?? 'wss://indexer.preprod.midnight.network/api/v4/graphql/ws',
  proofServer: process.env.PROOF_SERVER_URL ?? 'http://127.0.0.1:6300',
  node: process.env.NODE_URL ?? 'https://rpc.preprod.midnight.network',
} as const;

const SEED_FILE = new URL('../.env.deploy', import.meta.url).pathname;

/**
 * Reads the deploy seed, generating one on first run.
 *
 * The seed is written straight to a gitignored file and is never returned to a
 * caller that prints it — only the public address is ever displayed.
 */
export function loadSeed(): string {
  if (existsSync(SEED_FILE)) {
    const match = readFileSync(SEED_FILE, 'utf8').match(/^DEPLOY_SEED=([0-9a-f]{64})$/m);
    if (match !== null) return match[1];
  }
  const seed = Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('hex');
  writeFileSync(SEED_FILE, `# Generated by scripts/wallet.ts. Never commit or print this file.\nDEPLOY_SEED=${seed}\n`, { mode: 0o600 });
  chmodSync(SEED_FILE, 0o600);
  process.stdout.write(`new deploy wallet seed written to .env.deploy (gitignored, chmod 600)\n`);
  return seed;
}

export async function openWallet() {
  const wallet = await WalletBuilder.build(
    ENDPOINTS.indexer,
    ENDPOINTS.indexerWs,
    ENDPOINTS.proofServer,
    ENDPOINTS.node,
    loadSeed(),
    NetworkId.TestNet,
    'warn',
  );
  wallet.start();
  return wallet;
}

export function firstState(wallet: { state: () => { subscribe: (f: (s: unknown) => void) => { unsubscribe: () => void } } }) {
  return new Promise<Record<string, unknown>>((resolve) => {
    const sub = wallet.state().subscribe((s) => {
      resolve(s as Record<string, unknown>);
      sub.unsubscribe();
    });
  });
}
